### ISSUE TITLE
can't run build:wc

### ISSUE THREAD

**Issue by tcoopman** [bmomberger-bitovi/web-components-consumer#1]
This is the error after I cloned this repo:
```
[typescript] @rollup/plugin-typescript: Couldn't process compiler options (x2)
file:///home/thomas/Workspace/github/web-components-consumer/node_modules/rollup/dist/es/shared/node-entry.js:2287
        base = Object.assign(new Error(base.message), base);
                             ^

Error [RollupError]: @rollup/plugin-typescript: Couldn't process compiler options
    at error (file:///home/thomas/Workspace/github/web-components-consumer/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
    at Object.error (file:///home/thomas/Workspace/github/web-components-consumer/node_modules/rollup/dist/es/shared/node-entry.js:25268:20)
    at emitParsedOptionsErrors (file:///home/thomas/Workspace/github/web-components-consumer/node_modules/@rollup/plugin-typescript/dist/es/index.js:355:17)
    at Object.buildStart (file:///home/thomas/Workspace/github/web-components-consumer/node_modules/@rollup/plugin-typescript/dist/es/index.js:759:13)
    at file:///home/thomas/Workspace/github/web-components-consumer/node_modules/rollup/dist/es/shared/node-entry.js:25461:40
    at async Promise.all (index 5)
    at async PluginDriver.hookParallel (file:///home/thomas/Workspace/github/web-components-consumer/node_modules/rollup/dist/es/shared/node-entry.js:25389:9)
    at async file:///home/thomas/Workspace/github/web-components-consumer/node_modules/rollup/dist/es/shared/node-entry.js:26613:13
    at async catchUnfinishedHookActions (file:///home/thomas/Workspace/github/web-components-consumer/node_modules/rollup/dist/es/shared/node-entry.js:25827:16)
    at async rollupInternal (file:///home/thomas/Workspace/github/web-components-consumer/node_modules/rollup/dist/es/shared/node-entry.js:26610:5) {
  code: 'PLUGIN_ERROR',
  plugin: 'typescript',
  hook: 'buildStart'
}

Node.js v20.7.0
```

**Comment by bmomberger-bitovi** [comment]
The `build:wc` script is an artifact from this repo having been cloned from [bmomberger-bitovi/web-components-example](/bmomberger-bitovi/web-components-example).  This consumer repo (this repo) no longer has the source files needed to build the web components.

**Comment by bmomberger-bitovi** [comment]
I've deleted the unusable scripts.  Closing.
